#!/usr/bin/python
##
# Example builind script
# @author : Devresse Adrien
# @version : v0.1
# @date 08/04/2011

Import('*')	# import SConstruct exported var
import os
import random
import shutil
import commands

src_tests_link = ['gfal_srm_ifce']
src_tests_global = ["#src/common/gfal_common_errverbose.c"]
src_tests_voms = ["common/voms/gfal__test_voms.c","#src/common/voms/gfal_voms_if.c" ]
src_tests_srm = ["#src/common/gfal_common_srm.c", "common/gfal__test_common_srm.c"]
src_tests= ["common/gfal__test_verbose.c", "common/gfal__test_catalog.c","#src/common/gfal_common_catalog.c" ,"unit_test.c" ]
src_tests_all = src_tests+ src_tests_voms + src_tests_global + src_tests_srm 
## build test config

env_test.PrependENVPath('LD_LIBRARY_PATH', libs) # setup internal env LD PATH
env_test.Append(LIBS=src_tests_link);
test1 =env_test.Program("test_verbose",  src_tests_all+ [ccheck_lib])
run_test= env_test.Alias("test_run_verbose.passed", test1, test1[0].abspath)
test_alias= env_test.Alias("test", ["test_run_verbose.passed"])	
AlwaysBuild(test_alias)

