#!/usr/bin/python
##
# Example builind script
# @author : Devresse Adrien
# @version : v0.2
# @date 21/03/2011

Import('*')	# import SConstruct exported var
import os
import random
import shutil
import commands

src = ['example/gfal_testrw.c']
src2 = ['example/gfal_testread.c']
src3 = ['example/gfal_testdir.c']
src4 = ['example/gfal_testchmod.c']
src5 = ['example/gfal_testcreatedir.c']
src6 = ['example/gfal_teststat.c']
src7 = ['example/gfal_testget.c']


	

