/* /home/adevress/myworkspace/gfal/src/edg-local-replica-catalog.h
   Generated by wsdl2h 1.2.6b from /home/adevress/myworkspace/gfal/src/edg-local-replica-catalog.wsdl and /home/adevress/myworkspace/gfal/src/typemap-lrc.dat
   2011-04-05 08:13:02 GMT
   Copyright (C) 2001-2005 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

*/

/******************************************************************************\
 *                                                                            *
 * urn:edg-local-replica-catalog                                              *
 *                                                                            *
\******************************************************************************/

//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

lrc = "urn:edg-local-replica-catalog"
ns1 = "http://rls.data.edg.org"
ns2 = "http://attribute.util.data.edg.org"

*/

//gsoap ns1   schema namespace:	http://rls.data.edg.org
//gsoap ns2   schema namespace:	http://attribute.util.data.edg.org
//gsoap lrc   schema namespace:	urn:edg-local-replica-catalog
//gsoap ns1   schema form:	unqualified
//gsoap ns2   schema form:	unqualified
//gsoap lrc   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/


/// Built-in type "xs:boolean".
enum xsd__boolean { false_, true_ };

/// Built-in attribute "SOAP-ENC:arrayType".
typedef char* _SOAP_ENC__arrayType;


/// Typedef synonym for struct ns1__ColumnSizes.
typedef struct ns1__ColumnSizes ns1__ColumnSizes;

/// Typedef synonym for struct ArrayOf_USCOREsoapenc_USCOREstring.
typedef struct ArrayOf_USCOREsoapenc_USCOREstring ArrayOf_USCOREsoapenc_USCOREstring;

/// Typedef synonym for struct ns1__Metadata.
typedef struct ns1__Metadata ns1__Metadata;

/// Typedef synonym for struct ns2__AttributeDefinition.
typedef struct ns2__AttributeDefinition ns2__AttributeDefinition;

/// Typedef synonym for struct ns2__Mapping.
typedef struct ns2__Mapping ns2__Mapping;

/// Typedef synonym for struct ArrayOf_USCORExsd_USCOREstring.
typedef struct ArrayOf_USCORExsd_USCOREstring ArrayOf_USCORExsd_USCOREstring;

/// Typedef synonym for struct ArrayOf_USCOREtns1_USCOREAttributeDefinition.
typedef struct ArrayOf_USCOREtns1_USCOREAttributeDefinition ArrayOf_USCOREtns1_USCOREAttributeDefinition;

/// Typedef synonym for struct ArrayOf_USCOREtns1_USCOREMapping.
typedef struct ArrayOf_USCOREtns1_USCOREMapping ArrayOf_USCOREtns1_USCOREMapping;

/// "http://rls.data.edg.org":ColumnSizes is a complexType.
struct ns1__ColumnSizes
{
/// Element attributeDefinitionNameColumnSize of type xs:int.
    int                                  attributeDefinitionNameColumnSize 1;	///< Required element.
/// Element guidColumnSize of type xs:int.
    int                                  guidColumnSize                 1;	///< Required element.
/// Element pfnColumnSize of type xs:int.
    int                                  pfnColumnSize                  1;	///< Required element.
/// Element stringAttributeValueColumnSize of type xs:int.
    int                                  stringAttributeValueColumnSize 1;	///< Required element.
};

/// "http://rls.data.edg.org":Metadata is a complexType.
struct ns1__Metadata
{
/// Element columnSizes of type "http://rls.data.edg.org":ColumnSizes.
    struct ns1__ColumnSizes*             columnSizes                   ;	///< Nullable pointer.
/// Element countGuid of type xs:int.
    int                                  countGuid                      1;	///< Required element.
/// Element countPfn of type xs:int.
    int                                  countPfn                       1;	///< Required element.
};

/// "http://attribute.util.data.edg.org":AttributeDefinition is a complexType.
struct ns2__AttributeDefinition
{
/// Element name of type xs:string.
    char*                                name                          ;	///< Nullable pointer.
/// Element type of type xs:string.
    char*                                type                          ;	///< Nullable pointer.
};

/// "http://attribute.util.data.edg.org":Mapping is a complexType.
struct ns2__Mapping
{
/// Element attributeNames of type "http://rls.data.edg.org":ArrayOf_soapenc_string.
    struct ArrayOf_USCOREsoapenc_USCOREstring*  attributeNames                ;	///< Nullable pointer.
/// Element attributes of type "http://rls.data.edg.org":ArrayOf_soapenc_string.
    struct ArrayOf_USCOREsoapenc_USCOREstring*  attributes                    ;	///< Nullable pointer.
/// Element entry of type xs:string.
    char*                                entry                         ;	///< Nullable pointer.
/// Element guid of type xs:string.
    char*                                guid                          ;	///< Nullable pointer.
/// Element guidAttributeNames of type "http://rls.data.edg.org":ArrayOf_soapenc_string.
    struct ArrayOf_USCOREsoapenc_USCOREstring*  guidAttributeNames            ;	///< Nullable pointer.
/// Element guidAttributes of type "http://rls.data.edg.org":ArrayOf_soapenc_string.
    struct ArrayOf_USCOREsoapenc_USCOREstring*  guidAttributes                ;	///< Nullable pointer.
};

/// "http://rls.data.edg.org":ArrayOf_soapenc_string is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct ArrayOf_USCOREsoapenc_USCOREstring
{
/// Pointer to array of char*.
    char*                               *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:edg-local-replica-catalog":ArrayOf_xsd_string is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct ArrayOf_USCORExsd_USCOREstring
{
/// Pointer to array of char*.
    char*                               *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:edg-local-replica-catalog":ArrayOf_tns1_AttributeDefinition is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "http://attribute.util.data.edg.org":AttributeDefinition
struct ArrayOf_USCOREtns1_USCOREAttributeDefinition
{
/// Pointer to array of struct ns2__AttributeDefinition*.
    struct ns2__AttributeDefinition*    *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:edg-local-replica-catalog":ArrayOf_tns1_Mapping is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "http://attribute.util.data.edg.org":Mapping
struct ArrayOf_USCOREtns1_USCOREMapping
{
/// Pointer to array of struct ns2__Mapping*.
    struct ns2__Mapping*                *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap lrc  service name:	edg_local_replica_catalogSoapBinding 
//gsoap lrc  service type:	EdgLocalReplicaCatalog 
//gsoap lrc  service port:	http://rlscert02.cern.ch:7777/dteam/v2.2/edg-local-replica-catalog/services/edg-local-replica-catalog 
//gsoap lrc  service namespace:	urn:edg-local-replica-catalog 
//gsoap lrc  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Bindings
  - @ref edg_local_replica_catalogSoapBinding

*/

/**

@page edg_local_replica_catalogSoapBinding Binding "edg_local_replica_catalogSoapBinding"

@section edg_local_replica_catalogSoapBinding_operations Operations of Binding  "edg_local_replica_catalogSoapBinding"
  - @ref lrc__removeMapping
  - @ref lrc__getVersion
  - @ref lrc__addMapping
  - @ref lrc__getSchemaVersion
  - @ref lrc__deleteMapping
  - @ref lrc__guidExists
  - @ref lrc__pfnExists
  - @ref lrc__getPfns
  - @ref lrc__guidForPfn
  - @ref lrc__createAttributeDefinition
  - @ref lrc__createAttributeDefinition_
  - @ref lrc__getAttributeDefinition
  - @ref lrc__getAttributeDefinitions
  - @ref lrc__removeAttributeDefinition
  - @ref lrc__attributeDefinitionExists
  - @ref lrc__setPfnAttribute
  - @ref lrc__setStringPfnAttribute
  - @ref lrc__setIntPfnAttribute
  - @ref lrc__setFloatPfnAttribute
  - @ref lrc__setDatePfnAttribute
  - @ref lrc__getPfnAttribute
  - @ref lrc__getStringPfnAttribute
  - @ref lrc__getIntPfnAttribute
  - @ref lrc__getFloatPfnAttribute
  - @ref lrc__getDatePfnAttribute
  - @ref lrc__removePfnAttribute
  - @ref lrc__setDefaultResultLength
  - @ref lrc__getDefaultResultLength
  - @ref lrc__getColumnSizes
  - @ref lrc__getMappingsByGuid
  - @ref lrc__getMappingsByGuid_
  - @ref lrc__getMappingsByGuid__
  - @ref lrc__getMappingsByPfn
  - @ref lrc__getMappingsByPfn_
  - @ref lrc__getMappingsByPfn__
  - @ref lrc__getMappingsByAttribute
  - @ref lrc__getMappingsByAttribute_
  - @ref lrc__getMappingsByAttribute__
  - @ref lrc__getMappingsByPfnAttribute
  - @ref lrc__getMappingsByPfnAttribute_
  - @ref lrc__getMappingsByPfnAttribute__
  - @ref lrc__addRLISubscription
  - @ref lrc__addRLISubscription_
  - @ref lrc__removeRLISubscription
  - @ref lrc__getRLISubscriptions
  - @ref lrc__forceRLIUpdate
  - @ref lrc__ping
  - @ref lrc__getInterfaceVersion
  - @ref lrc__getMappingsWithAttributes
  - @ref lrc__getMappingsWithAttributes_
  - @ref lrc__getMetadata

@section edg_local_replica_catalogSoapBinding_ports Endpoints of Binding  "edg_local_replica_catalogSoapBinding"
  - http://rlscert02.cern.ch:7777/dteam/v2.2/edg-local-replica-catalog/services/edg-local-replica-catalog

*/

/******************************************************************************\
 *                                                                            *
 * edg_local_replica_catalogSoapBinding                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * lrc__removeMapping                                                         *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__removeMappingResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__removeMapping"
struct lrc__removeMappingResponse
{
};

/// Operation "lrc__removeMapping" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__removeMapping(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__removeMappingResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	removeMapping rpc
//gsoap lrc  service method-encoding:	removeMapping http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	removeMapping ""
int lrc__removeMapping(
    char*                               _in0,
    char*                               _in1,
    struct lrc__removeMappingResponse  * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getVersion                                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getVersionResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getVersion"
struct lrc__getVersionResponse
{
    char*                               getVersionReturn;
};

/// Operation "lrc__getVersion" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getVersion(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__getVersionResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getVersion rpc
//gsoap lrc  service method-encoding:	getVersion http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getVersion ""
int lrc__getVersion(
    struct lrc__getVersionResponse     * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__addMapping                                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__addMappingResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__addMapping"
struct lrc__addMappingResponse
{
};

/// Operation "lrc__addMapping" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__addMapping(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__addMappingResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	addMapping rpc
//gsoap lrc  service method-encoding:	addMapping http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	addMapping ""
int lrc__addMapping(
    char*                               _in0,
    char*                               _in1,
    struct lrc__addMappingResponse     * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getSchemaVersion                                                      *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getSchemaVersionResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getSchemaVersion"
struct lrc__getSchemaVersionResponse
{
    char*                               getSchemaVersionReturn;
};

/// Operation "lrc__getSchemaVersion" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getSchemaVersion(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__getSchemaVersionResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getSchemaVersion rpc
//gsoap lrc  service method-encoding:	getSchemaVersion http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getSchemaVersion ""
int lrc__getSchemaVersion(
    struct lrc__getSchemaVersionResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__deleteMapping                                                         *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__deleteMappingResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__deleteMapping"
struct lrc__deleteMappingResponse
{
};

/// Operation "lrc__deleteMapping" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__deleteMapping(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__deleteMappingResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	deleteMapping rpc
//gsoap lrc  service method-encoding:	deleteMapping http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	deleteMapping ""
int lrc__deleteMapping(
    char*                               _in0,
    struct lrc__deleteMappingResponse  * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__guidExists                                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__guidExistsResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__guidExists"
struct lrc__guidExistsResponse
{
    enum xsd__boolean                   _guidExistsReturn;
};

/// Operation "lrc__guidExists" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__guidExists(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__guidExistsResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	guidExists rpc
//gsoap lrc  service method-encoding:	guidExists http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	guidExists ""
int lrc__guidExists(
    char*                               _in0,
    struct lrc__guidExistsResponse     * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__pfnExists                                                             *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__pfnExistsResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__pfnExists"
struct lrc__pfnExistsResponse
{
    enum xsd__boolean                   _pfnExistsReturn;
};

/// Operation "lrc__pfnExists" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__pfnExists(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__pfnExistsResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	pfnExists rpc
//gsoap lrc  service method-encoding:	pfnExists http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	pfnExists ""
int lrc__pfnExists(
    char*                               _in0,
    struct lrc__pfnExistsResponse      * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getPfns                                                               *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getPfnsResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getPfns"
struct lrc__getPfnsResponse
{
    struct ArrayOf_USCORExsd_USCOREstring* _getPfnsReturn;
};

/// Operation "lrc__getPfns" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getPfns(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getPfnsResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getPfns rpc
//gsoap lrc  service method-encoding:	getPfns http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getPfns ""
int lrc__getPfns(
    char*                               _in0,
    struct lrc__getPfnsResponse        * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__guidForPfn                                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__guidForPfnResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__guidForPfn"
struct lrc__guidForPfnResponse
{
    char*                               _guidForPfnReturn;
};

/// Operation "lrc__guidForPfn" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__guidForPfn(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__guidForPfnResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	guidForPfn rpc
//gsoap lrc  service method-encoding:	guidForPfn http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	guidForPfn ""
int lrc__guidForPfn(
    char*                               _in0,
    struct lrc__guidForPfnResponse     * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__createAttributeDefinition                                             *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__createAttributeDefinitionResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__createAttributeDefinition"
struct lrc__createAttributeDefinitionResponse
{
};

/// Operation "lrc__createAttributeDefinition" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__createAttributeDefinition(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct ns2__AttributeDefinition*    in0,
    // response parameters:
    struct lrc__createAttributeDefinitionResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	createAttributeDefinition rpc
//gsoap lrc  service method-encoding:	createAttributeDefinition http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	createAttributeDefinition ""
int lrc__createAttributeDefinition(
    struct ns2__AttributeDefinition*    _in0,
    struct lrc__createAttributeDefinitionResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__createAttributeDefinition_                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__createAttributeDefinitionResponse_" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__createAttributeDefinition_"
struct lrc__createAttributeDefinitionResponse_
{
};

/// Operation "lrc__createAttributeDefinition_" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__createAttributeDefinition_(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct ns2__AttributeDefinition*    in0,
    // response parameters:
    struct lrc__createAttributeDefinitionResponse_*
  );
@endcode

*/

//gsoap lrc  service method-style:	createAttributeDefinition_ rpc
//gsoap lrc  service method-encoding:	createAttributeDefinition_ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	createAttributeDefinition_ ""
int lrc__createAttributeDefinition_(
    struct ns2__AttributeDefinition*    _in0,
    struct lrc__createAttributeDefinitionResponse_* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getAttributeDefinition                                                *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getAttributeDefinitionResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getAttributeDefinition"
struct lrc__getAttributeDefinitionResponse
{
    struct ns2__AttributeDefinition*    _getAttributeDefinitionReturn;
};

/// Operation "lrc__getAttributeDefinition" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getAttributeDefinition(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getAttributeDefinitionResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getAttributeDefinition rpc
//gsoap lrc  service method-encoding:	getAttributeDefinition http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getAttributeDefinition ""
int lrc__getAttributeDefinition(
    char*                               _in0,
    struct lrc__getAttributeDefinitionResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getAttributeDefinitions                                               *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getAttributeDefinitionsResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getAttributeDefinitions"
struct lrc__getAttributeDefinitionsResponse
{
    struct ArrayOf_USCOREtns1_USCOREAttributeDefinition* getAttributeDefinitionsReturn;
};

/// Operation "lrc__getAttributeDefinitions" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getAttributeDefinitions(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__getAttributeDefinitionsResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getAttributeDefinitions rpc
//gsoap lrc  service method-encoding:	getAttributeDefinitions http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getAttributeDefinitions ""
int lrc__getAttributeDefinitions(
    struct lrc__getAttributeDefinitionsResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__removeAttributeDefinition                                             *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__removeAttributeDefinitionResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__removeAttributeDefinition"
struct lrc__removeAttributeDefinitionResponse
{
};

/// Operation "lrc__removeAttributeDefinition" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__removeAttributeDefinition(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__removeAttributeDefinitionResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	removeAttributeDefinition rpc
//gsoap lrc  service method-encoding:	removeAttributeDefinition http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	removeAttributeDefinition ""
int lrc__removeAttributeDefinition(
    char*                               _in0,
    struct lrc__removeAttributeDefinitionResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__attributeDefinitionExists                                             *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__attributeDefinitionExistsResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__attributeDefinitionExists"
struct lrc__attributeDefinitionExistsResponse
{
    enum xsd__boolean                   _attributeDefinitionExistsReturn;
};

/// Operation "lrc__attributeDefinitionExists" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__attributeDefinitionExists(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__attributeDefinitionExistsResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	attributeDefinitionExists rpc
//gsoap lrc  service method-encoding:	attributeDefinitionExists http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	attributeDefinitionExists ""
int lrc__attributeDefinitionExists(
    char*                               _in0,
    struct lrc__attributeDefinitionExistsResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__setPfnAttribute                                                       *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__setPfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__setPfnAttribute"
struct lrc__setPfnAttributeResponse
{
    char*                               _setPfnAttributeReturn;
};

/// Operation "lrc__setPfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__setPfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    char*                               in2,
    // response parameters:
    struct lrc__setPfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	setPfnAttribute rpc
//gsoap lrc  service method-encoding:	setPfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	setPfnAttribute ""
int lrc__setPfnAttribute(
    char*                               _in0,
    char*                               _in1,
    char*                               _in2,
    struct lrc__setPfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__setStringPfnAttribute                                                 *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__setStringPfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__setStringPfnAttribute"
struct lrc__setStringPfnAttributeResponse
{
    char*                               _setStringPfnAttributeReturn;
};

/// Operation "lrc__setStringPfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__setStringPfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    char*                               in2,
    // response parameters:
    struct lrc__setStringPfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	setStringPfnAttribute rpc
//gsoap lrc  service method-encoding:	setStringPfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	setStringPfnAttribute ""
int lrc__setStringPfnAttribute(
    char*                               _in0,
    char*                               _in1,
    char*                               _in2,
    struct lrc__setStringPfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__setIntPfnAttribute                                                    *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__setIntPfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__setIntPfnAttribute"
struct lrc__setIntPfnAttributeResponse
{
    int                                 _setIntPfnAttributeReturn;
};

/// Operation "lrc__setIntPfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__setIntPfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    int                                 in2,
    // response parameters:
    struct lrc__setIntPfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	setIntPfnAttribute rpc
//gsoap lrc  service method-encoding:	setIntPfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	setIntPfnAttribute ""
int lrc__setIntPfnAttribute(
    char*                               _in0,
    char*                               _in1,
    int                                 _in2,
    struct lrc__setIntPfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__setFloatPfnAttribute                                                  *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__setFloatPfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__setFloatPfnAttribute"
struct lrc__setFloatPfnAttributeResponse
{
    float                               _setFloatPfnAttributeReturn;
};

/// Operation "lrc__setFloatPfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__setFloatPfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    float                               in2,
    // response parameters:
    struct lrc__setFloatPfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	setFloatPfnAttribute rpc
//gsoap lrc  service method-encoding:	setFloatPfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	setFloatPfnAttribute ""
int lrc__setFloatPfnAttribute(
    char*                               _in0,
    char*                               _in1,
    float                               _in2,
    struct lrc__setFloatPfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__setDatePfnAttribute                                                   *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__setDatePfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__setDatePfnAttribute"
struct lrc__setDatePfnAttributeResponse
{
    char *                              _setDatePfnAttributeReturn;
};

/// Operation "lrc__setDatePfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__setDatePfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    char *                              in2,
    // response parameters:
    struct lrc__setDatePfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	setDatePfnAttribute rpc
//gsoap lrc  service method-encoding:	setDatePfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	setDatePfnAttribute ""
int lrc__setDatePfnAttribute(
    char*                               _in0,
    char*                               _in1,
    char *                              _in2,
    struct lrc__setDatePfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getPfnAttribute                                                       *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getPfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getPfnAttribute"
struct lrc__getPfnAttributeResponse
{
    char*                               _getPfnAttributeReturn;
};

/// Operation "lrc__getPfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getPfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__getPfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getPfnAttribute rpc
//gsoap lrc  service method-encoding:	getPfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getPfnAttribute ""
int lrc__getPfnAttribute(
    char*                               _in0,
    char*                               _in1,
    struct lrc__getPfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getStringPfnAttribute                                                 *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getStringPfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getStringPfnAttribute"
struct lrc__getStringPfnAttributeResponse
{
    char*                               _getStringPfnAttributeReturn;
};

/// Operation "lrc__getStringPfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getStringPfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__getStringPfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getStringPfnAttribute rpc
//gsoap lrc  service method-encoding:	getStringPfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getStringPfnAttribute ""
int lrc__getStringPfnAttribute(
    char*                               _in0,
    char*                               _in1,
    struct lrc__getStringPfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getIntPfnAttribute                                                    *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getIntPfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getIntPfnAttribute"
struct lrc__getIntPfnAttributeResponse
{
    int                                 _getIntPfnAttributeReturn;
};

/// Operation "lrc__getIntPfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getIntPfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__getIntPfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getIntPfnAttribute rpc
//gsoap lrc  service method-encoding:	getIntPfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getIntPfnAttribute ""
int lrc__getIntPfnAttribute(
    char*                               _in0,
    char*                               _in1,
    struct lrc__getIntPfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getFloatPfnAttribute                                                  *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getFloatPfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getFloatPfnAttribute"
struct lrc__getFloatPfnAttributeResponse
{
    float                               _getFloatPfnAttributeReturn;
};

/// Operation "lrc__getFloatPfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getFloatPfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__getFloatPfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getFloatPfnAttribute rpc
//gsoap lrc  service method-encoding:	getFloatPfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getFloatPfnAttribute ""
int lrc__getFloatPfnAttribute(
    char*                               _in0,
    char*                               _in1,
    struct lrc__getFloatPfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getDatePfnAttribute                                                   *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getDatePfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getDatePfnAttribute"
struct lrc__getDatePfnAttributeResponse
{
    char *                              _getDatePfnAttributeReturn;
};

/// Operation "lrc__getDatePfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getDatePfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__getDatePfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getDatePfnAttribute rpc
//gsoap lrc  service method-encoding:	getDatePfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getDatePfnAttribute ""
int lrc__getDatePfnAttribute(
    char*                               _in0,
    char*                               _in1,
    struct lrc__getDatePfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__removePfnAttribute                                                    *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__removePfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__removePfnAttribute"
struct lrc__removePfnAttributeResponse
{
};

/// Operation "lrc__removePfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__removePfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__removePfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	removePfnAttribute rpc
//gsoap lrc  service method-encoding:	removePfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	removePfnAttribute ""
int lrc__removePfnAttribute(
    char*                               _in0,
    char*                               _in1,
    struct lrc__removePfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__setDefaultResultLength                                                *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__setDefaultResultLengthResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__setDefaultResultLength"
struct lrc__setDefaultResultLengthResponse
{
};

/// Operation "lrc__setDefaultResultLength" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__setDefaultResultLength(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    int                                 in0,
    // response parameters:
    struct lrc__setDefaultResultLengthResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	setDefaultResultLength rpc
//gsoap lrc  service method-encoding:	setDefaultResultLength http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	setDefaultResultLength ""
int lrc__setDefaultResultLength(
    int                                 _in0,
    struct lrc__setDefaultResultLengthResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getDefaultResultLength                                                *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getDefaultResultLengthResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getDefaultResultLength"
struct lrc__getDefaultResultLengthResponse
{
    int                                 getDefaultResultLengthReturn;
};

/// Operation "lrc__getDefaultResultLength" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getDefaultResultLength(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__getDefaultResultLengthResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getDefaultResultLength rpc
//gsoap lrc  service method-encoding:	getDefaultResultLength http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getDefaultResultLength ""
int lrc__getDefaultResultLength(
    struct lrc__getDefaultResultLengthResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getColumnSizes                                                        *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getColumnSizesResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getColumnSizes"
struct lrc__getColumnSizesResponse
{
    struct ns1__ColumnSizes*            getColumnSizesReturn;
};

/// Operation "lrc__getColumnSizes" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getColumnSizes(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__getColumnSizesResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getColumnSizes rpc
//gsoap lrc  service method-encoding:	getColumnSizes http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getColumnSizes ""
int lrc__getColumnSizes(
    struct lrc__getColumnSizesResponse * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByGuid                                                     *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByGuidResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByGuid"
struct lrc__getMappingsByGuidResponse
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByGuidReturn;
};

/// Operation "lrc__getMappingsByGuid" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByGuid(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getMappingsByGuidResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByGuid rpc
//gsoap lrc  service method-encoding:	getMappingsByGuid http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByGuid ""
int lrc__getMappingsByGuid(
    char*                               _in0,
    struct lrc__getMappingsByGuidResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByGuid_                                                    *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByGuidResponse_" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByGuid_"
struct lrc__getMappingsByGuidResponse_
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByGuidReturn;
};

/// Operation "lrc__getMappingsByGuid_" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByGuid_(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getMappingsByGuidResponse_*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByGuid_ rpc
//gsoap lrc  service method-encoding:	getMappingsByGuid_ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByGuid_ ""
int lrc__getMappingsByGuid_(
    char*                               _in0,
    struct lrc__getMappingsByGuidResponse_* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByGuid__                                                   *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByGuidResponse__" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByGuid__"
struct lrc__getMappingsByGuidResponse__
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByGuidReturn;
};

/// Operation "lrc__getMappingsByGuid__" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByGuid__(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getMappingsByGuidResponse__*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByGuid__ rpc
//gsoap lrc  service method-encoding:	getMappingsByGuid__ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByGuid__ ""
int lrc__getMappingsByGuid__(
    char*                               _in0,
    struct lrc__getMappingsByGuidResponse__* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByPfn                                                      *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByPfnResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByPfn"
struct lrc__getMappingsByPfnResponse
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByPfnReturn;
};

/// Operation "lrc__getMappingsByPfn" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByPfn(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getMappingsByPfnResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByPfn rpc
//gsoap lrc  service method-encoding:	getMappingsByPfn http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByPfn ""
int lrc__getMappingsByPfn(
    char*                               _in0,
    struct lrc__getMappingsByPfnResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByPfn_                                                     *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByPfnResponse_" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByPfn_"
struct lrc__getMappingsByPfnResponse_
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByPfnReturn;
};

/// Operation "lrc__getMappingsByPfn_" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByPfn_(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getMappingsByPfnResponse_*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByPfn_ rpc
//gsoap lrc  service method-encoding:	getMappingsByPfn_ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByPfn_ ""
int lrc__getMappingsByPfn_(
    char*                               _in0,
    struct lrc__getMappingsByPfnResponse_* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByPfn__                                                    *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByPfnResponse__" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByPfn__"
struct lrc__getMappingsByPfnResponse__
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByPfnReturn;
};

/// Operation "lrc__getMappingsByPfn__" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByPfn__(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getMappingsByPfnResponse__*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByPfn__ rpc
//gsoap lrc  service method-encoding:	getMappingsByPfn__ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByPfn__ ""
int lrc__getMappingsByPfn__(
    char*                               _in0,
    struct lrc__getMappingsByPfnResponse__* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByAttribute                                                *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByAttribute"
struct lrc__getMappingsByAttributeResponse
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByAttributeReturn;
};

/// Operation "lrc__getMappingsByAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getMappingsByAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByAttribute rpc
//gsoap lrc  service method-encoding:	getMappingsByAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByAttribute ""
int lrc__getMappingsByAttribute(
    char*                               _in0,
    struct lrc__getMappingsByAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByAttribute_                                               *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByAttributeResponse_" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByAttribute_"
struct lrc__getMappingsByAttributeResponse_
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByAttributeReturn;
};

/// Operation "lrc__getMappingsByAttribute_" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByAttribute_(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getMappingsByAttributeResponse_*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByAttribute_ rpc
//gsoap lrc  service method-encoding:	getMappingsByAttribute_ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByAttribute_ ""
int lrc__getMappingsByAttribute_(
    char*                               _in0,
    struct lrc__getMappingsByAttributeResponse_* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByAttribute__                                              *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByAttributeResponse__" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByAttribute__"
struct lrc__getMappingsByAttributeResponse__
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByAttributeReturn;
};

/// Operation "lrc__getMappingsByAttribute__" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByAttribute__(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__getMappingsByAttributeResponse__*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByAttribute__ rpc
//gsoap lrc  service method-encoding:	getMappingsByAttribute__ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByAttribute__ ""
int lrc__getMappingsByAttribute__(
    char*                               _in0,
    struct lrc__getMappingsByAttributeResponse__* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByPfnAttribute                                             *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByPfnAttributeResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByPfnAttribute"
struct lrc__getMappingsByPfnAttributeResponse
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByPfnAttributeReturn;
};

/// Operation "lrc__getMappingsByPfnAttribute" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByPfnAttribute(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__getMappingsByPfnAttributeResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByPfnAttribute rpc
//gsoap lrc  service method-encoding:	getMappingsByPfnAttribute http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByPfnAttribute ""
int lrc__getMappingsByPfnAttribute(
    char*                               _in0,
    char*                               _in1,
    struct lrc__getMappingsByPfnAttributeResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByPfnAttribute_                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByPfnAttributeResponse_" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByPfnAttribute_"
struct lrc__getMappingsByPfnAttributeResponse_
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByPfnAttributeReturn;
};

/// Operation "lrc__getMappingsByPfnAttribute_" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByPfnAttribute_(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__getMappingsByPfnAttributeResponse_*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByPfnAttribute_ rpc
//gsoap lrc  service method-encoding:	getMappingsByPfnAttribute_ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByPfnAttribute_ ""
int lrc__getMappingsByPfnAttribute_(
    char*                               _in0,
    char*                               _in1,
    struct lrc__getMappingsByPfnAttributeResponse_* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsByPfnAttribute__                                           *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsByPfnAttributeResponse__" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsByPfnAttribute__"
struct lrc__getMappingsByPfnAttributeResponse__
{
    struct ArrayOf_USCORExsd_USCOREstring* _getMappingsByPfnAttributeReturn;
};

/// Operation "lrc__getMappingsByPfnAttribute__" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsByPfnAttribute__(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__getMappingsByPfnAttributeResponse__*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsByPfnAttribute__ rpc
//gsoap lrc  service method-encoding:	getMappingsByPfnAttribute__ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsByPfnAttribute__ ""
int lrc__getMappingsByPfnAttribute__(
    char*                               _in0,
    char*                               _in1,
    struct lrc__getMappingsByPfnAttributeResponse__* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__addRLISubscription                                                    *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__addRLISubscriptionResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__addRLISubscription"
struct lrc__addRLISubscriptionResponse
{
    enum xsd__boolean                   _addRLISubscriptionReturn;
};

/// Operation "lrc__addRLISubscription" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__addRLISubscription(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__addRLISubscriptionResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	addRLISubscription rpc
//gsoap lrc  service method-encoding:	addRLISubscription http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	addRLISubscription ""
int lrc__addRLISubscription(
    char*                               _in0,
    char*                               _in1,
    struct lrc__addRLISubscriptionResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__addRLISubscription_                                                   *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__addRLISubscriptionResponse_" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__addRLISubscription_"
struct lrc__addRLISubscriptionResponse_
{
    enum xsd__boolean                   _addRLISubscriptionReturn;
};

/// Operation "lrc__addRLISubscription_" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__addRLISubscription_(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    char*                               in1,
    // response parameters:
    struct lrc__addRLISubscriptionResponse_*
  );
@endcode

*/

//gsoap lrc  service method-style:	addRLISubscription_ rpc
//gsoap lrc  service method-encoding:	addRLISubscription_ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	addRLISubscription_ ""
int lrc__addRLISubscription_(
    char*                               _in0,
    char*                               _in1,
    struct lrc__addRLISubscriptionResponse_* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__removeRLISubscription                                                 *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__removeRLISubscriptionResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__removeRLISubscription"
struct lrc__removeRLISubscriptionResponse
{
    enum xsd__boolean                   _removeRLISubscriptionReturn;
};

/// Operation "lrc__removeRLISubscription" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__removeRLISubscription(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    // response parameters:
    struct lrc__removeRLISubscriptionResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	removeRLISubscription rpc
//gsoap lrc  service method-encoding:	removeRLISubscription http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	removeRLISubscription ""
int lrc__removeRLISubscription(
    char*                               _in0,
    struct lrc__removeRLISubscriptionResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getRLISubscriptions                                                   *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getRLISubscriptionsResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getRLISubscriptions"
struct lrc__getRLISubscriptionsResponse
{
    struct ArrayOf_USCORExsd_USCOREstring* getRLISubscriptionsReturn;
};

/// Operation "lrc__getRLISubscriptions" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getRLISubscriptions(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__getRLISubscriptionsResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getRLISubscriptions rpc
//gsoap lrc  service method-encoding:	getRLISubscriptions http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getRLISubscriptions ""
int lrc__getRLISubscriptions(
    struct lrc__getRLISubscriptionsResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__forceRLIUpdate                                                        *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__forceRLIUpdateResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__forceRLIUpdate"
struct lrc__forceRLIUpdateResponse
{
};

/// Operation "lrc__forceRLIUpdate" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__forceRLIUpdate(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__forceRLIUpdateResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	forceRLIUpdate rpc
//gsoap lrc  service method-encoding:	forceRLIUpdate http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	forceRLIUpdate ""
int lrc__forceRLIUpdate(
    struct lrc__forceRLIUpdateResponse * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__ping                                                                  *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__pingResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__ping"
struct lrc__pingResponse
{
    char*                               pingReturn;
};

/// Operation "lrc__ping" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__ping(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__pingResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	ping rpc
//gsoap lrc  service method-encoding:	ping http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	ping ""
int lrc__ping(
    struct lrc__pingResponse           * ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getInterfaceVersion                                                   *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getInterfaceVersionResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getInterfaceVersion"
struct lrc__getInterfaceVersionResponse
{
    char*                               getInterfaceVersionReturn;
};

/// Operation "lrc__getInterfaceVersion" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getInterfaceVersion(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__getInterfaceVersionResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getInterfaceVersion rpc
//gsoap lrc  service method-encoding:	getInterfaceVersion http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getInterfaceVersion ""
int lrc__getInterfaceVersion(
    struct lrc__getInterfaceVersionResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsWithAttributes                                             *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsWithAttributesResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsWithAttributes"
struct lrc__getMappingsWithAttributesResponse
{
    struct ArrayOf_USCOREtns1_USCOREMapping* _getMappingsWithAttributesReturn;
};

/// Operation "lrc__getMappingsWithAttributes" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsWithAttributes(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    int                                 in1,
    // response parameters:
    struct lrc__getMappingsWithAttributesResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsWithAttributes rpc
//gsoap lrc  service method-encoding:	getMappingsWithAttributes http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsWithAttributes ""
int lrc__getMappingsWithAttributes(
    char*                               _in0,
    int                                 _in1,
    struct lrc__getMappingsWithAttributesResponse* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMappingsWithAttributes_                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMappingsWithAttributesResponse_" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMappingsWithAttributes_"
struct lrc__getMappingsWithAttributesResponse_
{
    struct ArrayOf_USCOREtns1_USCOREMapping* _getMappingsWithAttributesReturn;
};

/// Operation "lrc__getMappingsWithAttributes_" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMappingsWithAttributes_(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               in0,
    int                                 in1,
    // response parameters:
    struct lrc__getMappingsWithAttributesResponse_*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMappingsWithAttributes_ rpc
//gsoap lrc  service method-encoding:	getMappingsWithAttributes_ http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMappingsWithAttributes_ ""
int lrc__getMappingsWithAttributes_(
    char*                               _in0,
    int                                 _in1,
    struct lrc__getMappingsWithAttributesResponse_* ///< response parameter
);

/******************************************************************************\
 *                                                                            *
 * lrc__getMetadata                                                           *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "lrc__getMetadataResponse" of service binding "edg_local_replica_catalogSoapBinding" operation "lrc__getMetadata"
struct lrc__getMetadataResponse
{
    struct ns1__Metadata*               getMetadataReturn;
};

/// Operation "lrc__getMetadata" of service binding "edg_local_replica_catalogSoapBinding"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call_lrc__getMetadata(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct lrc__getMetadataResponse*
  );
@endcode

*/

//gsoap lrc  service method-style:	getMetadata rpc
//gsoap lrc  service method-encoding:	getMetadata http://schemas.xmlsoap.org/soap/encoding/
//gsoap lrc  service method-action:	getMetadata ""
int lrc__getMetadata(
    struct lrc__getMetadataResponse    * ///< response parameter
);

/* End of /home/adevress/myworkspace/gfal/src/edg-local-replica-catalog.h */
