/* soapServerLib.c
   Generated by gSOAP 2.6.2 from srm.v2.1.2.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#define WITH_NOGLOBAL
#define SOAP_FMAC3 static
#include "soapC.c"
#include "soapServer.c"

/* end of soapServerLib.c */
