/* soapServer.c
   Generated by gSOAP 2.6.2 from srm.v2.1.2.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_BEGIN_NAMESPACE(soap)

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.6.2 2006-04-20 08:50:47 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
	unsigned int n = soap->max_keep_alive;
	do
	{	soap_begin(soap);
		if (!--n)
			soap->keep_alive = 0;
		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
				return soap_send_fault(soap);
			soap_closesock(soap);
			continue;
		}
		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap))
			return soap_send_fault(soap);
		
	} while (soap->keep_alive);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmReserveSpace"))
		return soap_serve_srm2__srmReserveSpace(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmReleaseSpace"))
		return soap_serve_srm2__srmReleaseSpace(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmUpdateSpace"))
		return soap_serve_srm2__srmUpdateSpace(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmCompactSpace"))
		return soap_serve_srm2__srmCompactSpace(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmGetSpaceMetaData"))
		return soap_serve_srm2__srmGetSpaceMetaData(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmChangeFileStorageType"))
		return soap_serve_srm2__srmChangeFileStorageType(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmGetSpaceToken"))
		return soap_serve_srm2__srmGetSpaceToken(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmSetPermission"))
		return soap_serve_srm2__srmSetPermission(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmReassignToUser"))
		return soap_serve_srm2__srmReassignToUser(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmCheckPermission"))
		return soap_serve_srm2__srmCheckPermission(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmMkdir"))
		return soap_serve_srm2__srmMkdir(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmRmdir"))
		return soap_serve_srm2__srmRmdir(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmRm"))
		return soap_serve_srm2__srmRm(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmLs"))
		return soap_serve_srm2__srmLs(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmMv"))
		return soap_serve_srm2__srmMv(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmPrepareToGet"))
		return soap_serve_srm2__srmPrepareToGet(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmPrepareToPut"))
		return soap_serve_srm2__srmPrepareToPut(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmCopy"))
		return soap_serve_srm2__srmCopy(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmRemoveFiles"))
		return soap_serve_srm2__srmRemoveFiles(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmReleaseFiles"))
		return soap_serve_srm2__srmReleaseFiles(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmPutDone"))
		return soap_serve_srm2__srmPutDone(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmAbortRequest"))
		return soap_serve_srm2__srmAbortRequest(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmAbortFiles"))
		return soap_serve_srm2__srmAbortFiles(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmSuspendRequest"))
		return soap_serve_srm2__srmSuspendRequest(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmResumeRequest"))
		return soap_serve_srm2__srmResumeRequest(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmStatusOfGetRequest"))
		return soap_serve_srm2__srmStatusOfGetRequest(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmStatusOfPutRequest"))
		return soap_serve_srm2__srmStatusOfPutRequest(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmStatusOfCopyRequest"))
		return soap_serve_srm2__srmStatusOfCopyRequest(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmGetRequestSummary"))
		return soap_serve_srm2__srmGetRequestSummary(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmExtendFileLifeTime"))
		return soap_serve_srm2__srmExtendFileLifeTime(soap);
	if (!soap_match_tag(soap, soap->tag, "srm2:srmGetRequestID"))
		return soap_serve_srm2__srmGetRequestID(soap);
	return soap->error = SOAP_NO_METHOD;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmReserveSpace(struct soap *soap)
{	struct srm2__srmReserveSpace soap_tmp_srm2__srmReserveSpace;
	struct srm2__srmReserveSpaceResponse_ param_1;
	soap_default_srm2__srmReserveSpaceResponse_(soap, &param_1);
	soap_default_srm2__srmReserveSpace(soap, &soap_tmp_srm2__srmReserveSpace);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmReserveSpace(soap, &soap_tmp_srm2__srmReserveSpace, "srm2:srmReserveSpace", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmReserveSpace(soap, soap_tmp_srm2__srmReserveSpace.srmReserveSpaceRequest, &param_1);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmReserveSpaceResponse_(soap, &param_1);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmReserveSpaceResponse_(soap, &param_1, "srm2:srmReserveSpaceResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmReserveSpaceResponse_(soap, &param_1, "srm2:srmReserveSpaceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmReleaseSpace(struct soap *soap)
{	struct srm2__srmReleaseSpace soap_tmp_srm2__srmReleaseSpace;
	struct srm2__srmReleaseSpaceResponse_ param_2;
	soap_default_srm2__srmReleaseSpaceResponse_(soap, &param_2);
	soap_default_srm2__srmReleaseSpace(soap, &soap_tmp_srm2__srmReleaseSpace);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmReleaseSpace(soap, &soap_tmp_srm2__srmReleaseSpace, "srm2:srmReleaseSpace", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmReleaseSpace(soap, soap_tmp_srm2__srmReleaseSpace.srmReleaseSpaceRequest, &param_2);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmReleaseSpaceResponse_(soap, &param_2);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmReleaseSpaceResponse_(soap, &param_2, "srm2:srmReleaseSpaceResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmReleaseSpaceResponse_(soap, &param_2, "srm2:srmReleaseSpaceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmUpdateSpace(struct soap *soap)
{	struct srm2__srmUpdateSpace soap_tmp_srm2__srmUpdateSpace;
	struct srm2__srmUpdateSpaceResponse_ param_3;
	soap_default_srm2__srmUpdateSpaceResponse_(soap, &param_3);
	soap_default_srm2__srmUpdateSpace(soap, &soap_tmp_srm2__srmUpdateSpace);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmUpdateSpace(soap, &soap_tmp_srm2__srmUpdateSpace, "srm2:srmUpdateSpace", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmUpdateSpace(soap, soap_tmp_srm2__srmUpdateSpace.srmUpdateSpaceRequest, &param_3);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmUpdateSpaceResponse_(soap, &param_3);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmUpdateSpaceResponse_(soap, &param_3, "srm2:srmUpdateSpaceResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmUpdateSpaceResponse_(soap, &param_3, "srm2:srmUpdateSpaceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmCompactSpace(struct soap *soap)
{	struct srm2__srmCompactSpace soap_tmp_srm2__srmCompactSpace;
	struct srm2__srmCompactSpaceResponse_ param_4;
	soap_default_srm2__srmCompactSpaceResponse_(soap, &param_4);
	soap_default_srm2__srmCompactSpace(soap, &soap_tmp_srm2__srmCompactSpace);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmCompactSpace(soap, &soap_tmp_srm2__srmCompactSpace, "srm2:srmCompactSpace", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmCompactSpace(soap, soap_tmp_srm2__srmCompactSpace.srmCompactSpaceRequest, &param_4);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmCompactSpaceResponse_(soap, &param_4);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmCompactSpaceResponse_(soap, &param_4, "srm2:srmCompactSpaceResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmCompactSpaceResponse_(soap, &param_4, "srm2:srmCompactSpaceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmGetSpaceMetaData(struct soap *soap)
{	struct srm2__srmGetSpaceMetaData soap_tmp_srm2__srmGetSpaceMetaData;
	struct srm2__srmGetSpaceMetaDataResponse_ param_5;
	soap_default_srm2__srmGetSpaceMetaDataResponse_(soap, &param_5);
	soap_default_srm2__srmGetSpaceMetaData(soap, &soap_tmp_srm2__srmGetSpaceMetaData);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmGetSpaceMetaData(soap, &soap_tmp_srm2__srmGetSpaceMetaData, "srm2:srmGetSpaceMetaData", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmGetSpaceMetaData(soap, soap_tmp_srm2__srmGetSpaceMetaData.srmGetSpaceMetaDataRequest, &param_5);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetSpaceMetaDataResponse_(soap, &param_5);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmGetSpaceMetaDataResponse_(soap, &param_5, "srm2:srmGetSpaceMetaDataResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetSpaceMetaDataResponse_(soap, &param_5, "srm2:srmGetSpaceMetaDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmChangeFileStorageType(struct soap *soap)
{	struct srm2__srmChangeFileStorageType soap_tmp_srm2__srmChangeFileStorageType;
	struct srm2__srmChangeFileStorageTypeResponse_ param_6;
	soap_default_srm2__srmChangeFileStorageTypeResponse_(soap, &param_6);
	soap_default_srm2__srmChangeFileStorageType(soap, &soap_tmp_srm2__srmChangeFileStorageType);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmChangeFileStorageType(soap, &soap_tmp_srm2__srmChangeFileStorageType, "srm2:srmChangeFileStorageType", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmChangeFileStorageType(soap, soap_tmp_srm2__srmChangeFileStorageType.srmChangeFileStorageTypeRequest, &param_6);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmChangeFileStorageTypeResponse_(soap, &param_6);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmChangeFileStorageTypeResponse_(soap, &param_6, "srm2:srmChangeFileStorageTypeResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmChangeFileStorageTypeResponse_(soap, &param_6, "srm2:srmChangeFileStorageTypeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmGetSpaceToken(struct soap *soap)
{	struct srm2__srmGetSpaceToken soap_tmp_srm2__srmGetSpaceToken;
	struct srm2__srmGetSpaceTokenResponse_ param_7;
	soap_default_srm2__srmGetSpaceTokenResponse_(soap, &param_7);
	soap_default_srm2__srmGetSpaceToken(soap, &soap_tmp_srm2__srmGetSpaceToken);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmGetSpaceToken(soap, &soap_tmp_srm2__srmGetSpaceToken, "srm2:srmGetSpaceToken", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmGetSpaceToken(soap, soap_tmp_srm2__srmGetSpaceToken.srmGetSpaceTokenRequest, &param_7);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetSpaceTokenResponse_(soap, &param_7);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmGetSpaceTokenResponse_(soap, &param_7, "srm2:srmGetSpaceTokenResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetSpaceTokenResponse_(soap, &param_7, "srm2:srmGetSpaceTokenResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmSetPermission(struct soap *soap)
{	struct srm2__srmSetPermission soap_tmp_srm2__srmSetPermission;
	struct srm2__srmSetPermissionResponse_ param_8;
	soap_default_srm2__srmSetPermissionResponse_(soap, &param_8);
	soap_default_srm2__srmSetPermission(soap, &soap_tmp_srm2__srmSetPermission);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmSetPermission(soap, &soap_tmp_srm2__srmSetPermission, "srm2:srmSetPermission", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmSetPermission(soap, soap_tmp_srm2__srmSetPermission.srmSetPermissionRequest, &param_8);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmSetPermissionResponse_(soap, &param_8);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmSetPermissionResponse_(soap, &param_8, "srm2:srmSetPermissionResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmSetPermissionResponse_(soap, &param_8, "srm2:srmSetPermissionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmReassignToUser(struct soap *soap)
{	struct srm2__srmReassignToUser soap_tmp_srm2__srmReassignToUser;
	struct srm2__srmReassignToUserResponse_ param_9;
	soap_default_srm2__srmReassignToUserResponse_(soap, &param_9);
	soap_default_srm2__srmReassignToUser(soap, &soap_tmp_srm2__srmReassignToUser);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmReassignToUser(soap, &soap_tmp_srm2__srmReassignToUser, "srm2:srmReassignToUser", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmReassignToUser(soap, soap_tmp_srm2__srmReassignToUser.srmReassignToUserRequest, &param_9);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmReassignToUserResponse_(soap, &param_9);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmReassignToUserResponse_(soap, &param_9, "srm2:srmReassignToUserResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmReassignToUserResponse_(soap, &param_9, "srm2:srmReassignToUserResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmCheckPermission(struct soap *soap)
{	struct srm2__srmCheckPermission soap_tmp_srm2__srmCheckPermission;
	struct srm2__srmCheckPermissionResponse_ param_10;
	soap_default_srm2__srmCheckPermissionResponse_(soap, &param_10);
	soap_default_srm2__srmCheckPermission(soap, &soap_tmp_srm2__srmCheckPermission);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmCheckPermission(soap, &soap_tmp_srm2__srmCheckPermission, "srm2:srmCheckPermission", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmCheckPermission(soap, soap_tmp_srm2__srmCheckPermission.srmCheckPermissionRequest, &param_10);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmCheckPermissionResponse_(soap, &param_10);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmCheckPermissionResponse_(soap, &param_10, "srm2:srmCheckPermissionResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmCheckPermissionResponse_(soap, &param_10, "srm2:srmCheckPermissionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmMkdir(struct soap *soap)
{	struct srm2__srmMkdir soap_tmp_srm2__srmMkdir;
	struct srm2__srmMkdirResponse_ param_11;
	soap_default_srm2__srmMkdirResponse_(soap, &param_11);
	soap_default_srm2__srmMkdir(soap, &soap_tmp_srm2__srmMkdir);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmMkdir(soap, &soap_tmp_srm2__srmMkdir, "srm2:srmMkdir", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmMkdir(soap, soap_tmp_srm2__srmMkdir.srmMkdirRequest, &param_11);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmMkdirResponse_(soap, &param_11);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmMkdirResponse_(soap, &param_11, "srm2:srmMkdirResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmMkdirResponse_(soap, &param_11, "srm2:srmMkdirResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmRmdir(struct soap *soap)
{	struct srm2__srmRmdir soap_tmp_srm2__srmRmdir;
	struct srm2__srmRmdirResponse_ param_12;
	soap_default_srm2__srmRmdirResponse_(soap, &param_12);
	soap_default_srm2__srmRmdir(soap, &soap_tmp_srm2__srmRmdir);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmRmdir(soap, &soap_tmp_srm2__srmRmdir, "srm2:srmRmdir", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmRmdir(soap, soap_tmp_srm2__srmRmdir.srmRmdirRequest, &param_12);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmRmdirResponse_(soap, &param_12);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmRmdirResponse_(soap, &param_12, "srm2:srmRmdirResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmRmdirResponse_(soap, &param_12, "srm2:srmRmdirResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmRm(struct soap *soap)
{	struct srm2__srmRm soap_tmp_srm2__srmRm;
	struct srm2__srmRmResponse_ param_13;
	soap_default_srm2__srmRmResponse_(soap, &param_13);
	soap_default_srm2__srmRm(soap, &soap_tmp_srm2__srmRm);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmRm(soap, &soap_tmp_srm2__srmRm, "srm2:srmRm", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmRm(soap, soap_tmp_srm2__srmRm.srmRmRequest, &param_13);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmRmResponse_(soap, &param_13);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmRmResponse_(soap, &param_13, "srm2:srmRmResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmRmResponse_(soap, &param_13, "srm2:srmRmResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmLs(struct soap *soap)
{	struct srm2__srmLs soap_tmp_srm2__srmLs;
	struct srm2__srmLsResponse_ param_14;
	soap_default_srm2__srmLsResponse_(soap, &param_14);
	soap_default_srm2__srmLs(soap, &soap_tmp_srm2__srmLs);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmLs(soap, &soap_tmp_srm2__srmLs, "srm2:srmLs", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmLs(soap, soap_tmp_srm2__srmLs.srmLsRequest, &param_14);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmLsResponse_(soap, &param_14);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmLsResponse_(soap, &param_14, "srm2:srmLsResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmLsResponse_(soap, &param_14, "srm2:srmLsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmMv(struct soap *soap)
{	struct srm2__srmMv soap_tmp_srm2__srmMv;
	struct srm2__srmMvResponse_ param_15;
	soap_default_srm2__srmMvResponse_(soap, &param_15);
	soap_default_srm2__srmMv(soap, &soap_tmp_srm2__srmMv);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmMv(soap, &soap_tmp_srm2__srmMv, "srm2:srmMv", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmMv(soap, soap_tmp_srm2__srmMv.srmMvRequest, &param_15);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmMvResponse_(soap, &param_15);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmMvResponse_(soap, &param_15, "srm2:srmMvResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmMvResponse_(soap, &param_15, "srm2:srmMvResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmPrepareToGet(struct soap *soap)
{	struct srm2__srmPrepareToGet soap_tmp_srm2__srmPrepareToGet;
	struct srm2__srmPrepareToGetResponse_ param_16;
	soap_default_srm2__srmPrepareToGetResponse_(soap, &param_16);
	soap_default_srm2__srmPrepareToGet(soap, &soap_tmp_srm2__srmPrepareToGet);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmPrepareToGet(soap, &soap_tmp_srm2__srmPrepareToGet, "srm2:srmPrepareToGet", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmPrepareToGet(soap, soap_tmp_srm2__srmPrepareToGet.srmPrepareToGetRequest, &param_16);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmPrepareToGetResponse_(soap, &param_16);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmPrepareToGetResponse_(soap, &param_16, "srm2:srmPrepareToGetResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmPrepareToGetResponse_(soap, &param_16, "srm2:srmPrepareToGetResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmPrepareToPut(struct soap *soap)
{	struct srm2__srmPrepareToPut soap_tmp_srm2__srmPrepareToPut;
	struct srm2__srmPrepareToPutResponse_ param_17;
	soap_default_srm2__srmPrepareToPutResponse_(soap, &param_17);
	soap_default_srm2__srmPrepareToPut(soap, &soap_tmp_srm2__srmPrepareToPut);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmPrepareToPut(soap, &soap_tmp_srm2__srmPrepareToPut, "srm2:srmPrepareToPut", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmPrepareToPut(soap, soap_tmp_srm2__srmPrepareToPut.srmPrepareToPutRequest, &param_17);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmPrepareToPutResponse_(soap, &param_17);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmPrepareToPutResponse_(soap, &param_17, "srm2:srmPrepareToPutResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmPrepareToPutResponse_(soap, &param_17, "srm2:srmPrepareToPutResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmCopy(struct soap *soap)
{	struct srm2__srmCopy soap_tmp_srm2__srmCopy;
	struct srm2__srmCopyResponse_ param_18;
	soap_default_srm2__srmCopyResponse_(soap, &param_18);
	soap_default_srm2__srmCopy(soap, &soap_tmp_srm2__srmCopy);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmCopy(soap, &soap_tmp_srm2__srmCopy, "srm2:srmCopy", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmCopy(soap, soap_tmp_srm2__srmCopy.srmCopyRequest, &param_18);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmCopyResponse_(soap, &param_18);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmCopyResponse_(soap, &param_18, "srm2:srmCopyResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmCopyResponse_(soap, &param_18, "srm2:srmCopyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmRemoveFiles(struct soap *soap)
{	struct srm2__srmRemoveFiles soap_tmp_srm2__srmRemoveFiles;
	struct srm2__srmRemoveFilesResponse_ param_19;
	soap_default_srm2__srmRemoveFilesResponse_(soap, &param_19);
	soap_default_srm2__srmRemoveFiles(soap, &soap_tmp_srm2__srmRemoveFiles);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmRemoveFiles(soap, &soap_tmp_srm2__srmRemoveFiles, "srm2:srmRemoveFiles", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmRemoveFiles(soap, soap_tmp_srm2__srmRemoveFiles.srmRemoveFilesRequest, &param_19);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmRemoveFilesResponse_(soap, &param_19);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmRemoveFilesResponse_(soap, &param_19, "srm2:srmRemoveFilesResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmRemoveFilesResponse_(soap, &param_19, "srm2:srmRemoveFilesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmReleaseFiles(struct soap *soap)
{	struct srm2__srmReleaseFiles soap_tmp_srm2__srmReleaseFiles;
	struct srm2__srmReleaseFilesResponse_ param_20;
	soap_default_srm2__srmReleaseFilesResponse_(soap, &param_20);
	soap_default_srm2__srmReleaseFiles(soap, &soap_tmp_srm2__srmReleaseFiles);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmReleaseFiles(soap, &soap_tmp_srm2__srmReleaseFiles, "srm2:srmReleaseFiles", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmReleaseFiles(soap, soap_tmp_srm2__srmReleaseFiles.srmReleaseFilesRequest, &param_20);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmReleaseFilesResponse_(soap, &param_20);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmReleaseFilesResponse_(soap, &param_20, "srm2:srmReleaseFilesResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmReleaseFilesResponse_(soap, &param_20, "srm2:srmReleaseFilesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmPutDone(struct soap *soap)
{	struct srm2__srmPutDone soap_tmp_srm2__srmPutDone;
	struct srm2__srmPutDoneResponse_ param_21;
	soap_default_srm2__srmPutDoneResponse_(soap, &param_21);
	soap_default_srm2__srmPutDone(soap, &soap_tmp_srm2__srmPutDone);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmPutDone(soap, &soap_tmp_srm2__srmPutDone, "srm2:srmPutDone", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmPutDone(soap, soap_tmp_srm2__srmPutDone.srmPutDoneRequest, &param_21);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmPutDoneResponse_(soap, &param_21);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmPutDoneResponse_(soap, &param_21, "srm2:srmPutDoneResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmPutDoneResponse_(soap, &param_21, "srm2:srmPutDoneResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmAbortRequest(struct soap *soap)
{	struct srm2__srmAbortRequest soap_tmp_srm2__srmAbortRequest;
	struct srm2__srmAbortRequestResponse_ param_22;
	soap_default_srm2__srmAbortRequestResponse_(soap, &param_22);
	soap_default_srm2__srmAbortRequest(soap, &soap_tmp_srm2__srmAbortRequest);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmAbortRequest(soap, &soap_tmp_srm2__srmAbortRequest, "srm2:srmAbortRequest", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmAbortRequest(soap, soap_tmp_srm2__srmAbortRequest.srmAbortRequestRequest, &param_22);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmAbortRequestResponse_(soap, &param_22);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmAbortRequestResponse_(soap, &param_22, "srm2:srmAbortRequestResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmAbortRequestResponse_(soap, &param_22, "srm2:srmAbortRequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmAbortFiles(struct soap *soap)
{	struct srm2__srmAbortFiles soap_tmp_srm2__srmAbortFiles;
	struct srm2__srmAbortFilesResponse_ param_23;
	soap_default_srm2__srmAbortFilesResponse_(soap, &param_23);
	soap_default_srm2__srmAbortFiles(soap, &soap_tmp_srm2__srmAbortFiles);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmAbortFiles(soap, &soap_tmp_srm2__srmAbortFiles, "srm2:srmAbortFiles", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmAbortFiles(soap, soap_tmp_srm2__srmAbortFiles.srmAbortFilesRequest, &param_23);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmAbortFilesResponse_(soap, &param_23);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmAbortFilesResponse_(soap, &param_23, "srm2:srmAbortFilesResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmAbortFilesResponse_(soap, &param_23, "srm2:srmAbortFilesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmSuspendRequest(struct soap *soap)
{	struct srm2__srmSuspendRequest soap_tmp_srm2__srmSuspendRequest;
	struct srm2__srmSuspendRequestResponse_ param_24;
	soap_default_srm2__srmSuspendRequestResponse_(soap, &param_24);
	soap_default_srm2__srmSuspendRequest(soap, &soap_tmp_srm2__srmSuspendRequest);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmSuspendRequest(soap, &soap_tmp_srm2__srmSuspendRequest, "srm2:srmSuspendRequest", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmSuspendRequest(soap, soap_tmp_srm2__srmSuspendRequest.srmSuspendRequestRequest, &param_24);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmSuspendRequestResponse_(soap, &param_24);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmSuspendRequestResponse_(soap, &param_24, "srm2:srmSuspendRequestResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmSuspendRequestResponse_(soap, &param_24, "srm2:srmSuspendRequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmResumeRequest(struct soap *soap)
{	struct srm2__srmResumeRequest soap_tmp_srm2__srmResumeRequest;
	struct srm2__srmResumeRequestResponse_ param_25;
	soap_default_srm2__srmResumeRequestResponse_(soap, &param_25);
	soap_default_srm2__srmResumeRequest(soap, &soap_tmp_srm2__srmResumeRequest);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmResumeRequest(soap, &soap_tmp_srm2__srmResumeRequest, "srm2:srmResumeRequest", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmResumeRequest(soap, soap_tmp_srm2__srmResumeRequest.srmResumeRequestRequest, &param_25);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmResumeRequestResponse_(soap, &param_25);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmResumeRequestResponse_(soap, &param_25, "srm2:srmResumeRequestResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmResumeRequestResponse_(soap, &param_25, "srm2:srmResumeRequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmStatusOfGetRequest(struct soap *soap)
{	struct srm2__srmStatusOfGetRequest soap_tmp_srm2__srmStatusOfGetRequest;
	struct srm2__srmStatusOfGetRequestResponse_ param_26;
	soap_default_srm2__srmStatusOfGetRequestResponse_(soap, &param_26);
	soap_default_srm2__srmStatusOfGetRequest(soap, &soap_tmp_srm2__srmStatusOfGetRequest);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmStatusOfGetRequest(soap, &soap_tmp_srm2__srmStatusOfGetRequest, "srm2:srmStatusOfGetRequest", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmStatusOfGetRequest(soap, soap_tmp_srm2__srmStatusOfGetRequest.srmStatusOfGetRequestRequest, &param_26);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfGetRequestResponse_(soap, &param_26);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmStatusOfGetRequestResponse_(soap, &param_26, "srm2:srmStatusOfGetRequestResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfGetRequestResponse_(soap, &param_26, "srm2:srmStatusOfGetRequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmStatusOfPutRequest(struct soap *soap)
{	struct srm2__srmStatusOfPutRequest soap_tmp_srm2__srmStatusOfPutRequest;
	struct srm2__srmStatusOfPutRequestResponse_ param_27;
	soap_default_srm2__srmStatusOfPutRequestResponse_(soap, &param_27);
	soap_default_srm2__srmStatusOfPutRequest(soap, &soap_tmp_srm2__srmStatusOfPutRequest);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmStatusOfPutRequest(soap, &soap_tmp_srm2__srmStatusOfPutRequest, "srm2:srmStatusOfPutRequest", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmStatusOfPutRequest(soap, soap_tmp_srm2__srmStatusOfPutRequest.srmStatusOfPutRequestRequest, &param_27);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfPutRequestResponse_(soap, &param_27);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmStatusOfPutRequestResponse_(soap, &param_27, "srm2:srmStatusOfPutRequestResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfPutRequestResponse_(soap, &param_27, "srm2:srmStatusOfPutRequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmStatusOfCopyRequest(struct soap *soap)
{	struct srm2__srmStatusOfCopyRequest soap_tmp_srm2__srmStatusOfCopyRequest;
	struct srm2__srmStatusOfCopyRequestResponse_ param_28;
	soap_default_srm2__srmStatusOfCopyRequestResponse_(soap, &param_28);
	soap_default_srm2__srmStatusOfCopyRequest(soap, &soap_tmp_srm2__srmStatusOfCopyRequest);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmStatusOfCopyRequest(soap, &soap_tmp_srm2__srmStatusOfCopyRequest, "srm2:srmStatusOfCopyRequest", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmStatusOfCopyRequest(soap, soap_tmp_srm2__srmStatusOfCopyRequest.srmStatusOfCopyRequestRequest, &param_28);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmStatusOfCopyRequestResponse_(soap, &param_28);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmStatusOfCopyRequestResponse_(soap, &param_28, "srm2:srmStatusOfCopyRequestResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmStatusOfCopyRequestResponse_(soap, &param_28, "srm2:srmStatusOfCopyRequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmGetRequestSummary(struct soap *soap)
{	struct srm2__srmGetRequestSummary soap_tmp_srm2__srmGetRequestSummary;
	struct srm2__srmGetRequestSummaryResponse_ param_29;
	soap_default_srm2__srmGetRequestSummaryResponse_(soap, &param_29);
	soap_default_srm2__srmGetRequestSummary(soap, &soap_tmp_srm2__srmGetRequestSummary);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmGetRequestSummary(soap, &soap_tmp_srm2__srmGetRequestSummary, "srm2:srmGetRequestSummary", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmGetRequestSummary(soap, soap_tmp_srm2__srmGetRequestSummary.srmGetRequestSummaryRequest, &param_29);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetRequestSummaryResponse_(soap, &param_29);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmGetRequestSummaryResponse_(soap, &param_29, "srm2:srmGetRequestSummaryResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetRequestSummaryResponse_(soap, &param_29, "srm2:srmGetRequestSummaryResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmExtendFileLifeTime(struct soap *soap)
{	struct srm2__srmExtendFileLifeTime soap_tmp_srm2__srmExtendFileLifeTime;
	struct srm2__srmExtendFileLifeTimeResponse_ param_30;
	soap_default_srm2__srmExtendFileLifeTimeResponse_(soap, &param_30);
	soap_default_srm2__srmExtendFileLifeTime(soap, &soap_tmp_srm2__srmExtendFileLifeTime);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmExtendFileLifeTime(soap, &soap_tmp_srm2__srmExtendFileLifeTime, "srm2:srmExtendFileLifeTime", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmExtendFileLifeTime(soap, soap_tmp_srm2__srmExtendFileLifeTime.srmExtendFileLifeTimeRequest, &param_30);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmExtendFileLifeTimeResponse_(soap, &param_30);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmExtendFileLifeTimeResponse_(soap, &param_30, "srm2:srmExtendFileLifeTimeResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmExtendFileLifeTimeResponse_(soap, &param_30, "srm2:srmExtendFileLifeTimeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_srm2__srmGetRequestID(struct soap *soap)
{	struct srm2__srmGetRequestID soap_tmp_srm2__srmGetRequestID;
	struct srm2__srmGetRequestIDResponse_ param_31;
	soap_default_srm2__srmGetRequestIDResponse_(soap, &param_31);
	soap_default_srm2__srmGetRequestID(soap, &soap_tmp_srm2__srmGetRequestID);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_get_srm2__srmGetRequestID(soap, &soap_tmp_srm2__srmGetRequestID, "srm2:srmGetRequestID", NULL);
	if (soap->error)
		return soap->error;
	
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = srm2__srmGetRequestID(soap, soap_tmp_srm2__srmGetRequestID.srmGetRequestIDRequest, &param_31);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_srm2__srmGetRequestIDResponse_(soap, &param_31);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_srm2__srmGetRequestIDResponse_(soap, &param_31, "srm2:srmGetRequestIDResponse", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	};
	if (soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_srm2__srmGetRequestIDResponse_(soap, &param_31, "srm2:srmGetRequestIDResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap->error;
	soap_closesock(soap);
	return SOAP_OK;
}

SOAP_END_NAMESPACE(soap)

#ifdef __cplusplus
}
#endif

/* end of soapServer.c */
