/* soapsrmSoapBindingObject.h
   Generated by gSOAP 2.6.2 from srm.v2.1.2.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/

#ifndef soapsrmSoapBinding_H
#define soapsrmSoapBinding_H
#include "soapH.h"
SOAP_BEGIN_NAMESPACE(soap)
class srmSoapBinding : public soap
{    public:
	srmSoapBinding() { soap_init(this); };
	~srmSoapBinding() { soap_destroy(this); soap_end(this); soap_done(this); };
	int serve() { return soap_serve(this); };
};
SOAP_END_NAMESPACE(soap)
#endif
