/* soapsrmSoapBindingProxy.h
   Generated by gSOAP 2.6.2 from srm.v2.1.2.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/

#ifndef soapsrmSoapBinding_H
#define soapsrmSoapBinding_H
#include "soapH.h"
SOAP_BEGIN_NAMESPACE(soap)
class srmSoapBinding
{   public:
	struct soap *soap;
	const char *endpoint;
	srmSoapBinding() { soap = soap_new(); endpoint = "httpg://localhost:8443/ogsa/services"; };
	virtual ~srmSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_done(soap); SOAP_FREE((void*)soap); } };
	virtual int srm2__srmReserveSpace(struct srm2__srmReserveSpaceRequest *srmReserveSpaceRequest, struct srm2__srmReserveSpaceResponse_ *param_1) { return soap ? soap_call_srm2__srmReserveSpace(soap, endpoint, NULL, srmReserveSpaceRequest, param_1) : SOAP_EOM; };
	virtual int srm2__srmReleaseSpace(struct srm2__srmReleaseSpaceRequest *srmReleaseSpaceRequest, struct srm2__srmReleaseSpaceResponse_ *param_2) { return soap ? soap_call_srm2__srmReleaseSpace(soap, endpoint, NULL, srmReleaseSpaceRequest, param_2) : SOAP_EOM; };
	virtual int srm2__srmUpdateSpace(struct srm2__srmUpdateSpaceRequest *srmUpdateSpaceRequest, struct srm2__srmUpdateSpaceResponse_ *param_3) { return soap ? soap_call_srm2__srmUpdateSpace(soap, endpoint, NULL, srmUpdateSpaceRequest, param_3) : SOAP_EOM; };
	virtual int srm2__srmCompactSpace(struct srm2__srmCompactSpaceRequest *srmCompactSpaceRequest, struct srm2__srmCompactSpaceResponse_ *param_4) { return soap ? soap_call_srm2__srmCompactSpace(soap, endpoint, NULL, srmCompactSpaceRequest, param_4) : SOAP_EOM; };
	virtual int srm2__srmGetSpaceMetaData(struct srm2__srmGetSpaceMetaDataRequest *srmGetSpaceMetaDataRequest, struct srm2__srmGetSpaceMetaDataResponse_ *param_5) { return soap ? soap_call_srm2__srmGetSpaceMetaData(soap, endpoint, NULL, srmGetSpaceMetaDataRequest, param_5) : SOAP_EOM; };
	virtual int srm2__srmChangeFileStorageType(struct srm2__srmChangeFileStorageTypeRequest *srmChangeFileStorageTypeRequest, struct srm2__srmChangeFileStorageTypeResponse_ *param_6) { return soap ? soap_call_srm2__srmChangeFileStorageType(soap, endpoint, NULL, srmChangeFileStorageTypeRequest, param_6) : SOAP_EOM; };
	virtual int srm2__srmGetSpaceToken(struct srm2__srmGetSpaceTokenRequest *srmGetSpaceTokenRequest, struct srm2__srmGetSpaceTokenResponse_ *param_7) { return soap ? soap_call_srm2__srmGetSpaceToken(soap, endpoint, NULL, srmGetSpaceTokenRequest, param_7) : SOAP_EOM; };
	virtual int srm2__srmSetPermission(struct srm2__srmSetPermissionRequest *srmSetPermissionRequest, struct srm2__srmSetPermissionResponse_ *param_8) { return soap ? soap_call_srm2__srmSetPermission(soap, endpoint, NULL, srmSetPermissionRequest, param_8) : SOAP_EOM; };
	virtual int srm2__srmReassignToUser(struct srm2__srmReassignToUserRequest *srmReassignToUserRequest, struct srm2__srmReassignToUserResponse_ *param_9) { return soap ? soap_call_srm2__srmReassignToUser(soap, endpoint, NULL, srmReassignToUserRequest, param_9) : SOAP_EOM; };
	virtual int srm2__srmCheckPermission(struct srm2__srmCheckPermissionRequest *srmCheckPermissionRequest, struct srm2__srmCheckPermissionResponse_ *param_10) { return soap ? soap_call_srm2__srmCheckPermission(soap, endpoint, NULL, srmCheckPermissionRequest, param_10) : SOAP_EOM; };
	virtual int srm2__srmMkdir(struct srm2__srmMkdirRequest *srmMkdirRequest, struct srm2__srmMkdirResponse_ *param_11) { return soap ? soap_call_srm2__srmMkdir(soap, endpoint, NULL, srmMkdirRequest, param_11) : SOAP_EOM; };
	virtual int srm2__srmRmdir(struct srm2__srmRmdirRequest *srmRmdirRequest, struct srm2__srmRmdirResponse_ *param_12) { return soap ? soap_call_srm2__srmRmdir(soap, endpoint, NULL, srmRmdirRequest, param_12) : SOAP_EOM; };
	virtual int srm2__srmRm(struct srm2__srmRmRequest *srmRmRequest, struct srm2__srmRmResponse_ *param_13) { return soap ? soap_call_srm2__srmRm(soap, endpoint, NULL, srmRmRequest, param_13) : SOAP_EOM; };
	virtual int srm2__srmLs(struct srm2__srmLsRequest *srmLsRequest, struct srm2__srmLsResponse_ *param_14) { return soap ? soap_call_srm2__srmLs(soap, endpoint, NULL, srmLsRequest, param_14) : SOAP_EOM; };
	virtual int srm2__srmMv(struct srm2__srmMvRequest *srmMvRequest, struct srm2__srmMvResponse_ *param_15) { return soap ? soap_call_srm2__srmMv(soap, endpoint, NULL, srmMvRequest, param_15) : SOAP_EOM; };
	virtual int srm2__srmPrepareToGet(struct srm2__srmPrepareToGetRequest *srmPrepareToGetRequest, struct srm2__srmPrepareToGetResponse_ *param_16) { return soap ? soap_call_srm2__srmPrepareToGet(soap, endpoint, NULL, srmPrepareToGetRequest, param_16) : SOAP_EOM; };
	virtual int srm2__srmPrepareToPut(struct srm2__srmPrepareToPutRequest *srmPrepareToPutRequest, struct srm2__srmPrepareToPutResponse_ *param_17) { return soap ? soap_call_srm2__srmPrepareToPut(soap, endpoint, NULL, srmPrepareToPutRequest, param_17) : SOAP_EOM; };
	virtual int srm2__srmCopy(struct srm2__srmCopyRequest *srmCopyRequest, struct srm2__srmCopyResponse_ *param_18) { return soap ? soap_call_srm2__srmCopy(soap, endpoint, NULL, srmCopyRequest, param_18) : SOAP_EOM; };
	virtual int srm2__srmRemoveFiles(struct srm2__srmRemoveFilesRequest *srmRemoveFilesRequest, struct srm2__srmRemoveFilesResponse_ *param_19) { return soap ? soap_call_srm2__srmRemoveFiles(soap, endpoint, NULL, srmRemoveFilesRequest, param_19) : SOAP_EOM; };
	virtual int srm2__srmReleaseFiles(struct srm2__srmReleaseFilesRequest *srmReleaseFilesRequest, struct srm2__srmReleaseFilesResponse_ *param_20) { return soap ? soap_call_srm2__srmReleaseFiles(soap, endpoint, NULL, srmReleaseFilesRequest, param_20) : SOAP_EOM; };
	virtual int srm2__srmPutDone(struct srm2__srmPutDoneRequest *srmPutDoneRequest, struct srm2__srmPutDoneResponse_ *param_21) { return soap ? soap_call_srm2__srmPutDone(soap, endpoint, NULL, srmPutDoneRequest, param_21) : SOAP_EOM; };
	virtual int srm2__srmAbortRequest(struct srm2__srmAbortRequestRequest *srmAbortRequestRequest, struct srm2__srmAbortRequestResponse_ *param_22) { return soap ? soap_call_srm2__srmAbortRequest(soap, endpoint, NULL, srmAbortRequestRequest, param_22) : SOAP_EOM; };
	virtual int srm2__srmAbortFiles(struct srm2__srmAbortFilesRequest *srmAbortFilesRequest, struct srm2__srmAbortFilesResponse_ *param_23) { return soap ? soap_call_srm2__srmAbortFiles(soap, endpoint, NULL, srmAbortFilesRequest, param_23) : SOAP_EOM; };
	virtual int srm2__srmSuspendRequest(struct srm2__srmSuspendRequestRequest *srmSuspendRequestRequest, struct srm2__srmSuspendRequestResponse_ *param_24) { return soap ? soap_call_srm2__srmSuspendRequest(soap, endpoint, NULL, srmSuspendRequestRequest, param_24) : SOAP_EOM; };
	virtual int srm2__srmResumeRequest(struct srm2__srmResumeRequestRequest *srmResumeRequestRequest, struct srm2__srmResumeRequestResponse_ *param_25) { return soap ? soap_call_srm2__srmResumeRequest(soap, endpoint, NULL, srmResumeRequestRequest, param_25) : SOAP_EOM; };
	virtual int srm2__srmStatusOfGetRequest(struct srm2__srmStatusOfGetRequestRequest *srmStatusOfGetRequestRequest, struct srm2__srmStatusOfGetRequestResponse_ *param_26) { return soap ? soap_call_srm2__srmStatusOfGetRequest(soap, endpoint, NULL, srmStatusOfGetRequestRequest, param_26) : SOAP_EOM; };
	virtual int srm2__srmStatusOfPutRequest(struct srm2__srmStatusOfPutRequestRequest *srmStatusOfPutRequestRequest, struct srm2__srmStatusOfPutRequestResponse_ *param_27) { return soap ? soap_call_srm2__srmStatusOfPutRequest(soap, endpoint, NULL, srmStatusOfPutRequestRequest, param_27) : SOAP_EOM; };
	virtual int srm2__srmStatusOfCopyRequest(struct srm2__srmStatusOfCopyRequestRequest *srmStatusOfCopyRequestRequest, struct srm2__srmStatusOfCopyRequestResponse_ *param_28) { return soap ? soap_call_srm2__srmStatusOfCopyRequest(soap, endpoint, NULL, srmStatusOfCopyRequestRequest, param_28) : SOAP_EOM; };
	virtual int srm2__srmGetRequestSummary(struct srm2__srmGetRequestSummaryRequest *srmGetRequestSummaryRequest, struct srm2__srmGetRequestSummaryResponse_ *param_29) { return soap ? soap_call_srm2__srmGetRequestSummary(soap, endpoint, NULL, srmGetRequestSummaryRequest, param_29) : SOAP_EOM; };
	virtual int srm2__srmExtendFileLifeTime(struct srm2__srmExtendFileLifeTimeRequest *srmExtendFileLifeTimeRequest, struct srm2__srmExtendFileLifeTimeResponse_ *param_30) { return soap ? soap_call_srm2__srmExtendFileLifeTime(soap, endpoint, NULL, srmExtendFileLifeTimeRequest, param_30) : SOAP_EOM; };
	virtual int srm2__srmGetRequestID(struct srm2__srmGetRequestIDRequest *srmGetRequestIDRequest, struct srm2__srmGetRequestIDResponse_ *param_31) { return soap ? soap_call_srm2__srmGetRequestID(soap, endpoint, NULL, srmGetRequestIDRequest, param_31) : SOAP_EOM; };
};
SOAP_END_NAMESPACE(soap)
#endif
